<?php
/** Guarded multi-step acceptance harness for provider-private client direct uploads. */
if ('1' !== getenv('KOOPO_APPT_CLIENT_MEDIA_UAT')) { fwrite(STDERR,"Set KOOPO_APPT_CLIENT_MEDIA_UAT=1.\n"); exit(2); }
$action=sanitize_key((string)getenv('KOOPO_APPT_CLIENT_MEDIA_ACTION'));$user_id=absint(getenv('KOOPO_APPT_CLIENT_MEDIA_USER_ID'));$provider_id=absint(getenv('KOOPO_APPT_CLIENT_MEDIA_PROVIDER_ID'));$resource_id=absint(getenv('KOOPO_APPT_CLIENT_MEDIA_RESOURCE_ID'));$client_id=absint(getenv('KOOPO_APPT_CLIENT_MEDIA_CLIENT_ID'));$session_id=sanitize_text_field((string)getenv('KOOPO_APPT_CLIENT_MEDIA_SESSION_ID'));
use Koopo_Appointments\DB;use Koopo_Appointments\Provider_Profiles;use Koopo_Appointments\Resources;
if($action==='prepare'){
  $stamp=gmdate('YmdHis').wp_rand(100,999);$user_id=wp_insert_user(['user_login'=>'koopo_client_media_'.$stamp,'user_pass'=>wp_generate_password(32,true,true),'user_email'=>'koopo-client-media-'.$stamp.'@example.invalid','display_name'=>'Client Media UAT','role'=>'subscriber']);if(is_wp_error($user_id))throw new RuntimeException($user_id->get_error_message());update_user_meta($user_id,'_koopo_date_of_birth','1990-01-01');update_user_meta($user_id,'_koopo_age_status','adult');wp_set_current_user($user_id);
  $provider_id=(int)wp_insert_post(['post_type'=>Provider_Profiles::POST_TYPE,'post_status'=>'publish','post_title'=>'Client Media UAT','post_author'=>$user_id]);$resource_id=Resources::ensure_for_provider($provider_id);global $wpdb;$wpdb->insert(DB::clients_table(),['resource_id'=>$resource_id,'owner_user_id'=>$user_id,'name'=>'Private Client','email'=>'private-client@example.invalid']);$client_id=(int)$wpdb->insert_id;
  $request=new WP_REST_Request('POST','/koopo-media-gateway/v1/appointments/clients/'.$client_id.'/files/upload-sessions');$request->set_header('Idempotency-Key','koopo-client-media-'.$client_id.'-'.time());$request->set_header('content-type','application/json');$request->set_body(wp_json_encode(['filename'=>'private-reference.png','mimeType'=>'image/png','sizeBytes'=>absint(getenv('KOOPO_APPT_CLIENT_MEDIA_SIZE')),'kind'=>'image','clientRequestId'=>'koopo-client-media-'.$client_id]));$response=rest_do_request($request);echo wp_json_encode(['userId'=>$user_id,'providerId'=>$provider_id,'resourceId'=>$resource_id,'clientId'=>$client_id,'status'=>$response->get_status(),'session'=>$response->get_data()]);return;
}
if(!$user_id||!$provider_id||!$resource_id||!$client_id)throw new RuntimeException('Fixture identifiers are required.');wp_set_current_user($user_id);
if($action==='complete'){$request=new WP_REST_Request('POST','/koopo-media-gateway/v1/appointments/clients/'.$client_id.'/files/upload-sessions/'.$session_id.'/complete');$response=rest_do_request($request);$data=(array)$response->get_data();global $wpdb;$file=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.DB::client_files_table().' WHERE client_id=%d',$client_id));$encoded=wp_json_encode($data);echo wp_json_encode(['status'=>$response->get_status(),'clientFile'=>$data['clientFile']??null,'error'=>$response->get_status()>=400?['code'=>$data['code']??'','message'=>$data['message']??'']:null,'checks'=>['dbRow'=>(bool)$file,'assetId'=>(string)($file->asset_id??''),'wpAttachmentCount'=>(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.$wpdb->postmeta.' WHERE meta_key="_koopo_media_asset_id" AND meta_value=%s',(string)($file->asset_id??''))),'privatePayload'=>strpos($encoded,'deliveryUrl')===false&&strpos($encoded,'storageKey')===false&&strpos($encoded,'providerObjectId')===false]]);return;}
if($action==='cleanup'){global $wpdb;$files=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.DB::client_files_table().' WHERE client_id=%d',$client_id))?:[];foreach($files as $file){$request=new WP_REST_Request('DELETE','/koopo-media-gateway/v1/appointments/clients/'.$client_id.'/files/'.$file->id);$request->set_url_params(['client_id'=>$client_id,'file_id'=>(int)$file->id]);rest_do_request($request);}$wpdb->delete(DB::clients_table(),['id'=>$client_id]);$wpdb->delete(DB::resources_table(),['id'=>$resource_id]);wp_delete_post($provider_id,true);require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user($user_id);echo wp_json_encode(['cleaned'=>true,'clientId'=>$client_id]);return;}
throw new RuntimeException('Unknown action.');
