<?php defined('ABSPATH') || exit; ?>
<div class="dokan-dashboard-wrap">
  <?php do_action('dokan_dashboard_content_before'); ?>
  <div class="dokan-dashboard-content koopo-vendor-page koopo-clients-page">
    <header class="koopo-vendor-header"><div><span class="koopo-eyebrow"><?php esc_html_e('Private workspace', 'koopo-appointments'); ?></span><h2><?php esc_html_e('Clients & Forms', 'koopo-appointments'); ?></h2><p><?php esc_html_e('History, preferences, private notes, intake, and consent—organized around the client.', 'koopo-appointments'); ?></p></div><select class="koopo-input" data-client-context><option value=""><?php esc_html_e('Select booking profile…', 'koopo-appointments'); ?></option></select></header>
    <nav class="koopo-client-tabs" aria-label="<?php esc_attr_e('Client tools', 'koopo-appointments'); ?>"><button class="is-active" data-client-tab="records"><?php esc_html_e('Client records', 'koopo-appointments'); ?></button><button data-client-tab="forms"><?php esc_html_e('Intake & consent forms', 'koopo-appointments'); ?></button></nav>
    <section data-client-panel="records"><div class="koopo-client-layout"><div class="koopo-card" data-client-list><p><?php esc_html_e('Choose a booking profile.', 'koopo-appointments'); ?></p></div><div class="koopo-card" data-client-detail><div class="koopo-empty-state"><h3><?php esc_html_e('Select a client', 'koopo-appointments'); ?></h3><p><?php esc_html_e('Their appointment timeline and private provider context will appear here.', 'koopo-appointments'); ?></p></div></div></div></section>
    <section data-client-panel="forms" hidden><div class="koopo-client-layout"><div class="koopo-card" data-form-list></div><form class="koopo-card koopo-form-builder" data-form-builder><span class="koopo-eyebrow"><?php esc_html_e('New requirement', 'koopo-appointments'); ?></span><h3><?php esc_html_e('Create an intake or consent form', 'koopo-appointments'); ?></h3><label><?php esc_html_e('Title', 'koopo-appointments'); ?><input class="koopo-input" name="title" required></label><label><?php esc_html_e('Required for', 'koopo-appointments'); ?><select class="koopo-input" name="service_id" data-form-service><option value="0"><?php esc_html_e('All services', 'koopo-appointments'); ?></option></select></label><label><?php esc_html_e('Description', 'koopo-appointments'); ?><textarea class="koopo-input" name="description"></textarea></label><label><?php esc_html_e('Questions, one per line', 'koopo-appointments'); ?><textarea class="koopo-input" name="questions" placeholder="Allergies or sensitivities?&#10;What outcome are you hoping for?" required></textarea></label><div class="koopo-form-builder__row"><label><input type="checkbox" name="requires_signature"> <?php esc_html_e('Require electronic signature', 'koopo-appointments'); ?></label><label><?php esc_html_e('Request before appointment', 'koopo-appointments'); ?><select class="koopo-input" name="send_hours_before"><option value="0"><?php esc_html_e('Immediately', 'koopo-appointments'); ?></option><option value="24" selected>24 hours</option><option value="48">48 hours</option><option value="72">72 hours</option></select></label></div><button class="koopo-btn koopo-btn--gold" type="submit"><?php esc_html_e('Create form', 'koopo-appointments'); ?></button><span data-form-status role="status"></span></form></div></section>
  </div>
  <?php do_action('dokan_dashboard_content_after'); ?>
</div>
